name: Advanced Python Calculator

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

permissions:
  contents: read

jobs:
  set-environment: #this is a job named 'set-environment'
    runs-on: ubuntu-latest #your preferred OS
    steps:
      - name: Check if prod
        if: endsWith(github.ref, '/master') #if the triggering branch is 'master'
        run: |
          echo "ENVIRONMENT=PROD" >> $GITHUB_ENV
      - name: Check if dev
        if: endsWith(github.ref, '/develop') #if the triggering branch is 'dev'
        run: |
          echo "ENVIRONMENT=DEV" >> $GITHUB_ENV

  build:
    runs-on: ubuntu-latest
    environment: $GITHUB_ENV

    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      USERNAME: ${{ vars.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Debug environment variables
        run: |
          echo "ENVIRONMENT: ${{ vars.ENVIRONMENT }}"
          echo "USERNAME: ${{ vars.USERNAME }}"
          # Avoid printing sensitive information
          echo "PASSWORD is set"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest --pylint --cov
        run: |
          pytest --pylint --cov